### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by MehdiHellal** [itdev164-sp2019/mehdi-hellal-p1#3]
I have the attached error when I run my app in the server. Any Idea?

<img width="519" alt="1" src="https://user-images.githubusercontent.com/35744446/53981802-f213ac80-40d8-11e9-961a-5ef30d27277f.png">

**Comment by felixbec** [comment]
<img width="441" alt="screen shot 2019-03-07 at 1 10 09 pm" src="https://user-images.githubusercontent.com/43020476/53982944-c1814200-40db-11e9-88da-5b8f4e9d4bbd.png">
fix state in App.js from Ingredients to ingredients
